#设置服务器端编码
SET NAMES UTF8;

#删除数据库yw,如果存在
DROP DATABASE IF EXISTS ywvue;

#创建数据库ywvue
CREATE DATABASE ywvue CHARSET=UTF8;

#使用数据库ywvue
USE ywvue;

#创建数据表artist-作家
CREATE TABLE artist(
    aid INT PRIMARY KEY AUTO_INCREMENT,
    aname VARCHAR(10),
    info  VARCHAR(100),
    img VARCHAR(128)
);

#创建数据表product-作品
CREATE TABLE product(
    pid INT PRIMARY KEY AUTO_INCREMENT,      
    pname VARCHAR(20),				#作品名
    price DECIMAL(20,2),			#价钱
    atrist VARCHAR(20),				#作家
    material VARCHAR(20),			#材质
    size VARCHAR(20),				#尺寸
    timer VARCHAR(20),				#创作时间
    class VARCHAR(20),				#作品类型
    style VARCHAR(20),				#风格
    topic VARCHAR(20),				#题材
    shape VARCHAR(20),				#形状
    space VARCHAR(20),				#摆放空间
    lable VARCHAR(20),				#标签
    decoration VARCHAR(20),			#装裱费
    transport VARCHAR(20),			#运费
    is_recommend BOOLEAN,			#是否推荐
    rec_reason VARCHAR(1000),			#编辑推荐
    img VARCHAR(128),				#图片
    imgs VARCHAR(512),				#图集
	spaceshow VARCHAR(1000),		#场景展示
	otherdetail VARCHAR(128),		#其他细节展示
	buynotes VARCHAR(128),			#购买须知
	ywtips VARCHAR(128),			#艺网小贴士
    detail VARCHAR(10000)			#详情
);

#创建数据表article-文章
CREATE TABLE article(
    nid INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(268),				#文章标题
    tread VARCHAR(20),				#阅读量
    columns VARCHAR(20),			#所属栏目
    is_special BOOLEAN,				#是否推荐
	istop BOOLEAN,					#是否头条
	label VARCHAR(200),				#文章标签
    img VARCHAR(128),				#图片
    description VARCHAR(268),		#文章简介
    detail VARCHAR(3000)			#文章详情
);

#创建数据表user-用户信息
CREATE TABLE user(
    uid INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(20),				#用户名
    upwd VARCHAR(20)				#密码
);

#创建数据表shopcart-购物车
CREATE TABLE shopcart(
    cid INT PRIMARY KEY AUTO_INCREMENT,
    pid INT,					#商品ID
    uid INT,					#用户ID
    count INT,					#订单数量
    price DECIMAL(20,2),		#单价
    ctime DATETIME,				#加入时间
	isdel BOOLEAN DEFAULT 0		#是否删除
);

#创建数据表comment-评论
CREATE TABLE comment(
    mid INT PRIMARY KEY AUTO_INCREMENT,
    pid INT,				#作品ID
    uid INT,				#用户ID
    content VARCHAR(200),		#评论内容
    mtime DATETIME			#评论时间
);

#插入数据-artist作家
INSERT INTO artist VALUES(NULL,'谢雨桐','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-1.png');
INSERT INTO artist VALUES(NULL,'皮埃尔·奥古斯特·雷诺阿','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-2.jpg');
INSERT INTO artist VALUES(NULL,'王中林','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-3.jpg');
INSERT INTO artist VALUES(NULL,'陈东林','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-4.jpg');
INSERT INTO artist VALUES(NULL,'邓新黎','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-5.jpg');
INSERT INTO artist VALUES(NULL,'张占占','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-6.jpg');
INSERT INTO artist VALUES(NULL,'房徽','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-7.jpg');
INSERT INTO artist VALUES(NULL,'周艳峰','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-8.jpg');
INSERT INTO artist VALUES(NULL,'焦军','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-9.jpg');
INSERT INTO artist VALUES(NULL,'陈建国','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-10.jpg');
INSERT INTO artist VALUES(NULL,'贺秀','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-11.jpg');
INSERT INTO artist VALUES(NULL,'朱俊安','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-12.jpg');
INSERT INTO artist VALUES(NULL,'孙青','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-13.jpg');
INSERT INTO artist VALUES(NULL,'张雨晨','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-14.jpg');
INSERT INTO artist VALUES(NULL,'蔡鹏','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-15.jpg');
INSERT INTO artist VALUES(NULL,'李明琨','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-16.jpg');
INSERT INTO artist VALUES(NULL,'吴琼','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-17.jpg');
INSERT INTO artist VALUES(NULL,'严宝岩','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-18.jpg');
INSERT INTO artist VALUES(NULL,'吴琼','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-19.jpg');
INSERT INTO artist VALUES(NULL,'陈金庆','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-20.jpg');
INSERT INTO artist VALUES(NULL,'张琳','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-21.jpg');
INSERT INTO artist VALUES(NULL,'周明鉴','出生于山东日照，毕业于中国人民大学油画系','http://127.0.0.1:3008/images/goods/artist/artist-22.jpg');

#插入数据-user用户
INSERT INTO user VALUES(NULL,'13760436292','123456');
INSERT INTO user VALUES(NULL,'18670360781','123456');
INSERT INTO user VALUES(NULL,'649717442@qq.com','123456');

#插入数据-product作品
INSERT INTO product VALUES(NULL,"桃林",7550,"谢雨桐","布面油画","90,120","2018","油画","具象表现","风景","长方形","办公","原创,无装裱","如有装裱需求，请联系客服。","240",1,'“我想要这样一片桃林”；“日后，我为你种一片。”；“那我也要十里。”；“好......"。这是电视剧《三生三世十里桃花》里夜华与素素的对白。',"http://127.0.0.1:3008/images/goods/picture/1.jpg","http://127.0.0.1:3008/images/goods/picture/1.jpg,http://127.0.0.1:3008/images/goods/picture/1-2.jpg,http://127.0.0.1:3008/images/goods/picture/1-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/1.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/1-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"有少女的风景",7550,"皮埃尔·奥古斯特·雷诺阿","布面油画","21,15","约1875","油画","写实","风景","正方形","书房","原创,无装裱","如有装裱需求，请联系客服。","240",1,'“我想要这样一片桃林”；“日后，我为你种一片。”；“那我也要十里。”；“好......"。这是电视剧《三生三世十里桃花》里夜华与素素的对白。',"http://127.0.0.1:3008/images/goods/picture/2.jpg","http://127.0.0.1:3008/images/goods/picture/2.jpg,http://127.0.0.1:3008/images/goods/picture/2-2.jpg,http://127.0.0.1:3008/images/goods/picture/2-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/2.jpg"><div><p>霍夫曼（汉斯·霍夫曼，德裔美藉，抽象表现主义艺术的先驱。1966年去世后，其妻雷娜特·霍夫曼继承了他数量众多的收藏，其中主要为毕加索和雷诺阿）、纽约阿梅林杰和约埃画廊等收藏。</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/2-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/2-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"樱花摇影",25950,"王中林","雨露麻油画","120,80","2017","油画","写实","风景","正方形","办公","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家王中林是塞北风景油画创作的代表人物之一，他的作品质朴、纯粹。这幅《樱花摇影》中樱花在红墙的衬托下层层围珠玑，团团锦绣簇。',"http://127.0.0.1:3008/images/goods/picture/3.jpg","http://127.0.0.1:3008/images/goods/picture/3.jpg,http://127.0.0.1:3008/images/goods/picture/3-2.jpg,http://127.0.0.1:3008/images/goods/picture/3-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/3.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/3-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/3-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"异境NO·3",25950,"陈东林","雨露麻油画","60,90","2017","油画","抽象表现","风景","正方形","客厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'色彩与肌理呈现在艺术家陈东林的手上，可以轻松的拿捏到位，就像小孩玩玩具一样，透着好奇、专注、投入的劲儿，展现给你预料不到的视觉惊喜。作品《异境NO·3》颜料在画布上肆意碰撞挥洒、聚集，或稀薄融合，或细致点彩，种种对比并将画面视觉延伸至画面外，以抽象的形式将律动的激情表现的淋漓尽致。 ',"http://127.0.0.1:3008/images/goods/picture/4.jpg","http://127.0.0.1:3008/images/goods/picture/4.jpg,http://127.0.0.1:3008/images/goods/picture/4-2.jpg,http://127.0.0.1:3008/images/goods/picture/4-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/4.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/4-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/4-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"凤",2060,"邓新黎","数码版","60,90","2017","版画","超现实","动物","正方形","书房","原创,无装裱","如有装裱需求，请联系客服。","240",1,'作品《凤》呈现一个游走于中国神话与超现实想像之间的幻想世界，画面趣味性强。艺术家邓新黎曾经长时间居于新西兰深造及从事创作，所以他的作品既有传统的中国文化元素，又有西方艺术表现的痕迹，两者完美的融合加上艺术家细致的笔触、夸张的形象塑造、专业设计感的构图等，形成了一种视觉上的近乎漫画式的荒诞、幽默与刺激。 ',"http://127.0.0.1:3008/images/goods/picture/5.jpg","http://127.0.0.1:3008/images/goods/picture/5.jpg,http://127.0.0.1:3008/images/goods/picture/5-2.jpg,http://127.0.0.1:3008/images/goods/picture/5-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/5.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/5-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/5-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"一点温暖",2060,"张占占","丝网版画","69,98","2017","版画","卡通","动物","圆形","办公","原创,无装裱","如有装裱需求，请联系客服。","240",1,'张占占的画，总能用最简单质朴的东西打动你，让你的情绪大起大落，先是会觉得它可爱又萌萌的，然后就是深沉又安静，之后又会生出一种柔软微妙的情绪，这些感触是很难得的，一幅画的成功之处，就是要让观赏者欣赏出自己的味道来，而张占占做到了。 “孤独”是张占占的画里不可或缺的一个元素。人们常说，孤独才是人生的常态，但是没有真正的经历过生活的人，是很难切实的体会到这句话的分量的。 你是否渴望狂欢，期待一个拥抱呢，在艺术家张占占的作品中都是描述孤单，多么想在黑夜中可以有束光芒照射，有双温暖的双手轻抚，有朋友围着火堆跳舞呢。 ',"http://127.0.0.1:3008/images/goods/picture/6.jpg","http://127.0.0.1:3008/images/goods/picture/6.jpg,http://127.0.0.1:3008/images/goods/picture/6-2.jpg,http://127.0.0.1:3008/images/goods/picture/6-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/6.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/6-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/6-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"涟漪",2060,"房徽","丝网版画","69,98","2017","版画","具象表现","动物","其他","儿童房","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家房徽将对肖像的描写深化成一种纯正的物象，从而具有穿越时间空间的共性和不朽，极致细腻的描绘将人物层层雕琢，在注视的过程中，观者从被吸引到透过表面的平静到逐渐构建和丰富起面孔之下的物象变迁。  ',"http://127.0.0.1:3008/images/goods/picture/7.jpg","http://127.0.0.1:3008/images/goods/picture/7.jpg,http://127.0.0.1:3008/images/goods/picture/7-2.jpg,http://127.0.0.1:3008/images/goods/picture/7-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/7.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/7-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/7-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"寤",1800,"周艳峰","青铜着色","40,17,13","2016","版画","观念艺术","动物","正方形","走廊","原创,无装裱","如有装裱需求，请联系客服。","380",1,'艺术家周艳峰的《寤》系列作品手法精细，形象怪诞有趣，脱离常见所谓动物的面貌，造型极其可爱，加之青铜着色，实为各类装饰装点收藏提升格调之精品。',"http://127.0.0.1:3008/images/goods/picture/8.jpg","http://127.0.0.1:3008/images/goods/picture/8.jpg,http://127.0.0.1:3008/images/goods/picture/8-2.jpg,http://127.0.0.1:3008/images/goods/picture/8-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/8.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/8-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/8-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"门前翠屏图之一",3450,"焦军","丝网版画","69,98","2017","水墨","传统国画","山水","竖行","餐厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家焦军的作品境界深幽，层峦叠嶂，逶迤连绵，山水相容的院落悠闲中更显潇洒，在浩渺的水波下平添了一股超凡的逸气，与高山雄峰相映，使人无不产生一种陶醉感。',"http://127.0.0.1:3008/images/goods/picture/9.jpg","http://127.0.0.1:3008/images/goods/picture/9.jpg,http://127.0.0.1:3008/images/goods/picture/9-2.jpg,http://127.0.0.1:3008/images/goods/picture/9-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/9.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/9-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/9-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"雨洗秋山净",1620,"廖忠柳","丝网版画","45,70","2018","水墨","实验水墨","山水","竖行","书房","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家廖忠柳的作品《雨洗秋山净》笔触柔软，远处山脉连绵不断却又似乎融化在江河之中，树林与茅屋相辅相成，一江烟雨过后眼前的一切都变得虚无缥缈，竹林墨染，到底是烟雨使眼前化做水墨，还是水墨成就了烟雨。',"http://127.0.0.1:3008/images/goods/picture/10.png","http://127.0.0.1:3008/images/goods/picture/10.png,http://127.0.0.1:3008/images/goods/picture/10-2.png,http://127.0.0.1:3008/images/goods/picture/10-3.png",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/10.png"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/10-2.png"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/10-3.png"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"清夏",3450,"陈建国","纸本设色","69,98","2017","水墨","写意","山水","正方形","客厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家焦军的作品境界深幽，层峦叠嶂，逶迤连绵，山水相容的院落悠闲中更显潇洒，在浩渺的水波下平添了一股超凡的逸气，与高山雄峰相映，使人无不产生一种陶醉感。',"http://127.0.0.1:3008/images/goods/picture/11.jpg","http://127.0.0.1:3008/images/goods/picture/11.jpg,http://127.0.0.1:3008/images/goods/picture/11-2.jpg,http://127.0.0.1:3008/images/goods/picture/11-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/11.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/11-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/11-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"壁虎旅行记",3450,"贺秀","绢本设色","99,187","2017","水墨","工笔","风景","竖行","客厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家对空间场景有着独特的视角，描绘的是生活中真实环境与自然景观的融合，但通过构图的布局更为深邃，神秘，似乎挖掘出人性的内心深处。艺术家借以动物作为主观想象的表征，譬如壁虎，小小的身躯隐匿在场景之中，以一种窥视者，旁观者的角色游历各处，表现出“现实”与“自然”的和谐共处。',"http://127.0.0.1:3008/images/goods/picture/12.jpg","http://127.0.0.1:3008/images/goods/picture/12.jpg,http://127.0.0.1:3008/images/goods/picture/12-2.jpg,http://127.0.0.1:3008/images/goods/picture/12-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/12.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/12-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/12-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"乐谱画",2120,"朱俊安","绢本设色","23,33","2017","水彩(粉)","抽象","其他","其他","客厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家在作品《乐谱画》系列中以不同色彩去填充各种抽象的几何形状，像童趣十足的七巧板，在稚拙而执着的拼接中去验证心中明亮而自由的梦想，最后所有被触及的记忆便像画中鸽子似的形象般向远处飞去，迎着阳光洒下的温暖，灿烂一脸。',"http://127.0.0.1:3008/images/goods/picture/13.jpg","http://127.0.0.1:3008/images/goods/picture/13.jpg,http://127.0.0.1:3008/images/goods/picture/13-2.jpg,http://127.0.0.1:3008/images/goods/picture/13-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/13.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/13-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/13-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"春花",3260,"孙青","纸本水彩","50,50","2017","水彩(粉)","具象表现","其他","圆形","客厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'作品《春花》系列很好的运用了水彩的透明特质，描绘的花朵有种润的视觉舒适感，水彩“水”的感觉亦明显，细节上艺术家独特的技法几何分割，增添了几许时尚、现代感。',"http://127.0.0.1:3008/images/goods/picture/14.jpg","http://127.0.0.1:3008/images/goods/picture/14.jpg,http://127.0.0.1:3008/images/goods/picture/14-2.jpg,http://127.0.0.1:3008/images/goods/picture/14-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/14.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/14-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/14-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"童趣",3760,"张雨晨","纸本水彩","53,78","2015","水彩(粉)","超现实","山水","竖行","儿童房","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家最难能可贵之处就是始终保持着一颗天真的童心，小孩子最爱的气球已然承载起飞翔的梦想，咦~那一边又是谁给我寄来了云中礼呢？',"http://127.0.0.1:3008/images/goods/picture/15.png","http://127.0.0.1:3008/images/goods/picture/15.png,http://127.0.0.1:3008/images/goods/picture/15-2.png,http://127.0.0.1:3008/images/goods/picture/15-3.png",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/10.png"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/15-2.png"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/15-3.png"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"花",3260,"蔡鹏","纸本水彩","50,50","2016","水彩(粉)","写实","静物","长方形","走廊","原创,无装裱,独版,艺术家签名","如有装裱需求，请联系客服。","240",1,'作品以写实的手法将阳光下绽放的花朵真实呈现在观者眼前，它们迎接清晨的第一束光亮，也迎接你心系的希望，虽不似有力迸发，却在柔和而坚定的太阳光下给人心以暖意。花之美在绽放，画之美则在心中。',"http://127.0.0.1:3008/images/goods/picture/16.jpg","http://127.0.0.1:3008/images/goods/picture/16.jpg,http://127.0.0.1:3008/images/goods/picture/16-2.jpg,http://127.0.0.1:3008/images/goods/picture/16-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/16.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/16-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/16-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"群山设计",3200,"李明琨","布面丙烯","120,50","2017","油画","具象表现","风景","长方形","餐厅","原创,无装裱,艺术家签名","如有装裱需求，请联系客服。","240",1,'作品《群山设计》中三角形的巧妙组合显现出一股阳刚之气，这是个磁场强大的能量场，黑色吸金，黑色也代表看神秘，等你来探寻。',"http://127.0.0.1:3008/images/goods/picture/17.jpg","http://127.0.0.1:3008/images/goods/picture/17.jpg,http://127.0.0.1:3008/images/goods/picture/17-2.jpg,http://127.0.0.1:3008/images/goods/picture/17-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/17.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/17-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/17-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"雪山的来客",2980,"吴琼","pu+环保玻璃钢+纯羊皮","35,30,14","2017","衍生工艺","具象表现","人物","长方形","儿童房","原创,无装裱,艺术家签名","如有装裱需求，请联系客服。","240",1,'80后的吴琼不仅仅是一名画家，也是一名雕塑家，原创创意是艺术家独有的语言，他的作品里创造了许多感人有趣的孩童形象，观者可以跟随其回归到一种简单、纯粹的心灵状态，那轻昂起的头，微闭上的眼睛，代表了何等的满足与陶醉。每个人的童年轨迹是不同的，但都有着这相似的梦幻。',"http://127.0.0.1:3008/images/goods/picture/18.jpg","http://127.0.0.1:3008/images/goods/picture/18.jpg,http://127.0.0.1:3008/images/goods/picture/18-2.jpg,http://127.0.0.1:3008/images/goods/picture/18-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/18.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/18-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/18-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"远方系列",2980,"严宝岩","绢本设色","50,180","2018","当代水墨","实验水墨","人物","长方形","客厅","原创,无装裱,艺术家签名","如有装裱需求，请联系客服。","240",1,'红色的云朵充斥了整个画面，月亮也被晕染了一层红色，少女在空中遨游飞翔，像是一个甜美的梦，是少女赋有的色彩，艺术家用艺术的方式描绘了一个神话故事，虚幻缥缈的梦境。',"http://127.0.0.1:3008/images/goods/picture/19.jpg","http://127.0.0.1:3008/images/goods/picture/19.jpg,http://127.0.0.1:3008/images/goods/picture/19-2.jpg,http://127.0.0.1:3008/images/goods/picture/19-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/19.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/19-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/19-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"往事如风",2980,"吴琼","pu+环保玻璃钢","21,40,13","2017","衍生工艺","具象表现","人物","圆形","办公","原创,无装裱,艺术家签名","如有装裱需求，请联系客服。","240",1,'80后的吴琼不仅仅是一名画家，也是一名雕塑家，原创创意是艺术家独有的语言，他的作品里创造了许多感人有趣的孩童形象，观者可以跟随其回归到一种简单、纯粹的心灵状态，那轻昂起的头，微闭上的眼睛，代表了何等的满足与陶醉。每个人的童年轨迹是不同的，但都有着这相似的梦幻。',"http://127.0.0.1:3008/images/goods/picture/20.jpg","http://127.0.0.1:3008/images/goods/picture/20.jpg,http://127.0.0.1:3008/images/goods/picture/20-2.jpg,http://127.0.0.1:3008/images/goods/picture/20-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/20.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/20-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/20-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"逐浪飞花",60500,"陈金庆","不锈钢·24k金","32,80,22","2017","雕塑","观念艺术","静物","长方形","儿童房","原创,无装裱,艺术家签名","如有装裱需求，请联系客服。","240",1,'“无住生香”系列雕塑作品，艺术家陈金庆以他自身敏锐的艺术感受力，将对生命的理解和哲学的体悟融入在了作品中，表达了超越个体和时代生存的寓言性，这样的表现方式将观者带入一个简约却又极其丰富的视觉审美中。',"http://127.0.0.1:3008/images/goods/picture/21.jpg","http://127.0.0.1:3008/images/goods/picture/21.jpg,http://127.0.0.1:3008/images/goods/picture/21-2.jpg,http://127.0.0.1:3008/images/goods/picture/21-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/21.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/21-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/21-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"寓言",40540,"张琳","布面油画、丝线","180,150","2015","油画","抽象表现","其他","其他","餐厅","原创,无装裱,艺术家签名","如有装裱需求，请联系客服。","240",1,'80后的吴琼不仅仅是一名画家，也是一名雕塑家，原创创意是艺术家独有的语言，他的作品里创造了许多感人有趣的孩童形象，观者可以跟随其回归到一种简单、纯粹的心灵状态，那轻昂起的头，微闭上的眼睛，代表了何等的满足与陶醉。每个人的童年轨迹是不同的，但都有着这相似的梦幻。',"http://127.0.0.1:3008/images/goods/picture/22.jpg","http://127.0.0.1:3008/images/goods/picture/22.jpg,http://127.0.0.1:3008/images/goods/picture/22-2.jpg,http://127.0.0.1:3008/images/goods/picture/22-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/22.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/22-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/22-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');
INSERT INTO product VALUES(NULL,"星星",520,"周明鉴","黑白木刻版画","39,58","2017","版画","观念艺术","其他","正方形","客厅","原创,无装裱","如有装裱需求，请联系客服。","240",1,'艺术家焦军的作品境界深幽，层峦叠嶂，逶迤连绵，山水相容的院落悠闲中更显潇洒，在浩渺的水波下平添了一股超凡的逸气，与高山雄峰相映，使人无不产生一种陶醉感。',"http://127.0.0.1:3008/images/goods/picture/23.jpg","http://127.0.0.1:3008/images/goods/picture/23.jpg,http://127.0.0.1:3008/images/goods/picture/23-2.jpg,http://127.0.0.1:3008/images/goods/picture/23-3.jpg",'<img src="http://127.0.0.1:3008/images/goods/picture/show-1.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-2.jpg"><img src="http://127.0.0.1:3008/images/goods/picture/show-3.jpg">','<img src="http://127.0.0.1:3008/images/goods/picture/show-4.png">','<img src="http://127.0.0.1:3008/images/goods/picture/gmxz.png">','<img src="http://127.0.0.1:3008/images/goods/picture/ywxtzsc.png">','<div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/23.jpg"><div><p>王中林的塞北风景油画，质朴静远、境由心生。他的画作给人以自在平静之感，得益于其真情实感的流露，宁静、质朴，不矫饰、不刻意，给人舒适自在之感。这同时与画家的创作手法密不可分，画家对色彩与笔法的探索，也是他心境的表白：质朴、纯粹、不造作。——董占军</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/23-2.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div><div class="article-info-div"><img src="http://127.0.0.1:3008/images/goods/picture/23-3.jpg"><div><p>我的油画一直在变，是自然而然的内心需求，是一种内观，是危机，也是突破。近期的创作注重自身独立精神，艺术理念的自觉性，从内在挖掘表现形式，逐渐从具象人物自觉转变为抽象，画不再需要宏大叙事，巧妙的观念，或是敏感的政治题材，去掉一切，只需要简单的感知。——艺术家自述</p></div></div>');

#插入数据-article文章
INSERT INTO article VALUES(NULL,'展览现场 | 有光LET THERE BE LIGHT',389,'艺术生活',1,0,'艺网大拿,艺术生活','http://127.0.0.1:3008/images/news/news-1.png','YWART Art Center 将携手 FLUA™2018年9月23日为你呈现在地性艺术项目“有光”。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'不舍昼夜 NONE STOP | 展览详情',951,'艺网动态',1,0,'艺网大拿,艺网动态,近期热门','http://127.0.0.1:3008/images/news/news-2.png','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'ALL IN RED | 大红色凭什么经久不衰',9286,'艺术时尚',1,0,'艺网大拿,艺术时尚,艺术时尚热门','http://127.0.0.1:3008/images/news/news-3.jpg','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'持续燃烧的孤独感，谁给我一个熊抱？',2496,'艺术资讯',1,1,'艺网大拿,艺术资讯,艺术视野','http://127.0.0.1:3008/images/news/news-4.jpg','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'艺网双11囤画节，节日礼一站购全',2496,'专题推荐',1,0,'专题,艺术生活,APP首页','http://127.0.0.1:3008/images/news/news-5.jpg','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'艺周荐 |《怒》：我们要互相了解到什么程度，你才会相信我',2496,'艺术生活',0,0,'专题,艺术生活','http://127.0.0.1:3008/images/news/news-6.jpg','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'捧在手心里的，除了你，还有雕塑',2496,'艺术生活',0,0,'专题,艺术生活','http://127.0.0.1:3008/images/news/news-7.jpg','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>');
INSERT INTO article VALUES(NULL,'花好月圆夜，人间好时节',6376,'艺术生活',1,0,'专题,艺术生活','http://127.0.0.1:3008/images/news/news-8.jpg','保利时间博物馆携手艺网，共同呈现古今艺术展“不舍昼夜”。展览以时间为轴线，以传统艺术与当代艺术并置为线索，追溯历朝历代最具代表性传统艺术踪迹与其脉络，在与当代艺术的结合中，通过古今对比探讨中国当代艺术对于传统艺术的继承发扬与演变革新。','<p>YWART Art Center 将携手 FLUA™于2018年9月23日为你呈现在地性艺术项目“有光”。</p><p><img src="http://127.0.0.1:3008/images/news/article-1.jpg"></p><p><strong>艺术总监</strong> / 朱彤 王福霞</p><p><strong>策展人</strong> / 崔佳琦</p><p><strong>开幕时间</strong> / 2018.9.23 14:00</p><p><strong>展览时间</strong> / 2018.9.23-11.23</p><p><strong>展览地点</strong> /北京居然之家十里河店灯饰软装馆</p><p><strong>主办方</strong> / 艺网 / 金海棠</p><p>合作方 / 房天下/ 新浪艺术</p><p>有光，即区分黑暗。</p><p>从希腊神话中的盗取太阳神火种赠人类的普罗米修斯，到分离白昼与黑暗的耶和华，从燧人氏取火到1879年第一个电灯在纽约发出微光。有光，从一种想象，一种看得见摸不着的光学现象，变成了生产工具，变成生活用品。</p><p><img src="http://127.0.0.1:3008/images/news/article-2.jpg"></p><p>▲徐子薇作品&nbsp;未完成星球系列</p><p>有光在这里，是另一种场景的想象。&ldquo;有光&rdquo;发生在北京南四环十里河的灯饰城中，灯饰城汇集全国乃至世界各地大小品牌的灯饰店，所汇聚的店对于他们自身都有着众说不一的定位，从消费级别的灯饰，到&ldquo;艺术品级别&rdquo;的灯饰，高价格的包装下，装饰画的衬托下，三两盏灯上了天花板，合乎高端艺术生活方式的满意表情，写在店员的脸上，似有道理推销词里，也未曾发觉丝毫的不安。在这丝毫不安的外在下，存在的某种缺失的东西，却难溢于言表。在这里，艺术只是一个形容词，一种装饰手段，它们通过卖家的夸夸其谈，价格促销，将每一件灯具，每一种和自认为奢华的生活理念，送进了许多家庭。</p><p><img src="http://127.0.0.1:3008/images/news/article-3.jpg"></p><p>▲靓屋灯饰城外景</p><p>工业化及全球化的进程中，推动资源在不断进行整合，产品类别在不断细分。人们的生活亦是如此，在今天，想买一件沙发，可以在线上线下找到最稳妥的途径，购买到称心如意的产品。光照亮的不再是黑暗，不再是远古时代人们抬头仰望星辰的向往，不再是火光第一次迸发时的兴奋，它们成为工厂生产线上成千上万的生活用品，被国际标准化零件拼凑成冰冷的形态，光照亮的，只是索然无味的日常，于高速工业社会中日渐苍白的梦想。</p><p><img src="http://127.0.0.1:3008/images/news/article-4.jpg"></p><p>▲王韫琛作品 &nbsp;机械千手观音</p><p>从塑造灯光的艺术说起，无论是Dan Flavin空间内被称为&ldquo;光和色彩的场景&rdquo;，还是Tracey Emin展现其丰富个人经历手势的霓虹装置，光逐步展现其在艺术维度的衍生含义。而在今天，当我们再谈论艺术与空间，艺术的手段和形式时，不希望艺术只是&ldquo;光&rdquo;这样一个名词的前缀。&ldquo;光&rdquo;应该如实的投射消费社会的百态，从而丰富人们对商品价值与形式的认知。</p>')

